### ISSUE TITLE
Peningkatan pengelolaan website IKASTARA

### ISSUE THREAD

**Issue by firewalker06** [Ikastara/informatika#1]
Saat ini kita memiliki website IKASTARA di `ikastara.or.id` dengan WordPress yang kita kelola sendiri.

# Problem

- Kapasitas di website IKASTARA hampir memenuhi 93% dari total 1 GB. Sebagian besar adalah file foto dari 2 tahun terakhir
  <img src="https://user-images.githubusercontent.com/157515/47404940-82300580-d779-11e8-82d5-39f3eb170052.jpg" width="200" />
- WordPress belum diupdate ke terbaru 4.7.11, versi terbaru adalah 4.9.8
- Spam dan bruteforce, plugin WordFence tidak aktif
- Tidak aman oleh serangan _man-in-the-middle_ karena belum menggunakan `HTTPS`

# Solusi

Ada dua alternatif solusi, tetap di hosting dan atasi masalah yang ada atau pindah ke hosting lain:

## Tetap di hosting saat ini

- meningkatkan kapasitas hosting ke paket yang lebih besar, [Rp 100.000/bulan untuk 2GB](https://www.rumahweb.com/hosting-murah/)
- upgrade WordPress dan plugin ke versi terbaru
- aktifkan _LetsEncrypt_ untuk _SSL Encryption_

## Pindah ke WordPress.com

Personal package seharga [$ 4/bulan](https://wordpress.com/pricing/), sudah support custom domain.

Pros:

- kapasitas jauh lebih besar, 6GB
- dikelola oleh WordPress, sehingga:
  - tidak perlu khawatir dengan _brute force_ atau ragam _hacking_ lainnya
  - selalu up to date
  - otomatis HTTPS
- bagi yang memiliki akun WordPress bisa langsung bergabung sebagai kolaborator tanpa harus mendaftar akun lagi

Cons:

- perlu migrasi konten (bisa dengan wp-importer plugin)
- perlu mengarahkan domain utama ke WordPress.com
- opsi theme dan plugin terbatas
- Ada kebutuhan kustomisasi lebih dari sekedar blog (landing page, event posting, multi rubrik tulisan)

## Pindah ke _Cloud_?

Pindah ke _cloud service_ seperti AWS atau GCP tidak memberikan benefit yang signifikan karena kita tetap harus mengelola instance WordPress secara mandiri. Lagipula ongkosnya lebih mahal.

**Comment by leksa** [comment]
## Pindah ke WordPress.com
Cons : 
- Ada kebutuhan kustomisasi lebih dari sekedar blog (landing page, event posting, multi rubrik tulisan)

**Comment by firewalker06** [comment]
Purwarupa: https://ikastarabeta.wordpress.com/

Yang sudah dilakukan:

✅ impor konten dan media
✅ menyunting tema seadanya (menggunakan [tema DARA (gratis)](https://wordpress.com/theme/dara))
✅ mencoba "Featured Post" untuk menggunakan slide

Pros:

➕ unggahan konten dan media hanya menggunakan 2.3% dari kapasitas gratis
➕ proses migrasi cepat

Cons:

➖ belum bisa kustomisasi CSS (butuh akun Premium)
➖ pengguna tidak bisa diimpor karena harus harus dihubungkan dengan akun WordPress (bisa dihubungkan nanti)

Yang perlu dilakukan:

- [x] mengundang kontributor untuk mencoba

**Comment by firewalker06** [comment]
Percobaan singkat cukup memuaskan, bang Ferry sudah mencoba untuk membuat Featured post:

![screenshot_2018-11-06 ikastara](https://user-images.githubusercontent.com/157515/48040525-e3110200-e1ab-11e8-8a82-e8205c2e13ac.png)

**Comment by firewalker06** [comment]
Migrasi berhasil, untuk langkah selanjutnya akan dilanjutkan di #2.
